using Microsoft.CodeAnalysis;
using System.Text.RegularExpressions;

namespace X12Net.SourceGenerator;

/// <summary>
/// Roslyn incremental source generator that emits strongly-typed X12 transaction-set
/// classes and their key segment wrappers for all built-in schemas.
/// Schema data is loaded from the embedded resource <c>schemas/schema.json</c>;
/// adding a new transaction type requires only editing that file, not this generator.
/// </summary>
[Generator]
public sealed class X12TransactionGenerator : IIncrementalGenerator
{
    // ── IIncrementalGenerator ─────────────────────────────────────────────

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static ctx =>
        {
            var (segments, transactions) = LoadSchema();

            foreach (var seg in segments)
                ctx.AddSource($"{seg.ClassName}.g.cs", BuildSegmentSource(seg));

            foreach (var tx in transactions)
                ctx.AddSource($"{tx.ClassName}.g.cs", BuildTxSource(tx, segments));
        });
    }

    // ── Code emission ─────────────────────────────────────────────────────

    private static string BuildSegmentSource(SegmentDesc seg)
    {
        var props = new System.Text.StringBuilder();
        foreach (var p in seg.Properties)
        {
            props.AppendLine($"        /// <summary>{p.Doc}.</summary>");
            props.AppendLine($"        public string {p.Name} => Raw[{p.Index}];");
            props.AppendLine();
        }

        return $$"""
            // <auto-generated/>
            #nullable enable
            namespace X12Net.Transactions
            {
                /// <summary>Typed wrapper for the {{seg.SegmentId}} segment.</summary>
                public sealed class {{seg.ClassName}}
                {
                    internal {{seg.ClassName}}(global::X12Net.Core.X12Segment raw) => Raw = raw;

                    /// <summary>The underlying raw segment.</summary>
                    public global::X12Net.Core.X12Segment Raw { get; }

            {{props}}    }
            }
            """;
    }

    private static string BuildTxSource(TxDesc tx, SegmentDesc[] segments)
    {
        var segId = GetSegId(segments, tx.SegClassName);
        return $$"""
            // <auto-generated/>
            #nullable enable
            namespace X12Net.Transactions
            {
                /// <summary>Strongly-typed wrapper for the {{tx.TxSetId}} transaction set.</summary>
                public sealed class {{tx.ClassName}}
                {
                    private {{tx.ClassName}}({{tx.SegClassName}}? keySegment, global::X12Net.DOM.X12Document document)
                    {
                        {{tx.PropertyName}} = keySegment;
                        Document            = document;
                    }

                    /// <summary>The first typed {{segId}} segment, or <c>null</c> if none is present.</summary>
                    public {{tx.SegClassName}}? {{tx.PropertyName}} { get; }

                    /// <summary>The underlying generic document for full access.</summary>
                    public global::X12Net.DOM.X12Document Document { get; }

                    /// <summary>Returns all {{segId}} segments in document order.</summary>
                    public global::System.Collections.Generic.IEnumerable<{{tx.SegClassName}}> All{{tx.PropertyName}}()
                    {
                        foreach (var seg in Document.AllSegments("{{segId}}"))
                            yield return new {{tx.SegClassName}}(new global::X12Net.Core.X12Segment(seg.SegmentId, seg.Elements));
                    }

                    /// <summary>Parses a {{tx.TxSetId}} transaction from raw EDI X12 text.</summary>
                    public static {{tx.ClassName}} Parse(string input)
                    {
                        var doc = global::X12Net.DOM.X12Document.Parse(input);
                        var raw = doc.Segments.FirstOrDefault(s => s.SegmentId == "{{segId}}");
                        var found = raw is null ? null
                            : new {{tx.SegClassName}}(new global::X12Net.Core.X12Segment(raw.SegmentId, raw.Elements));
                        return new {{tx.ClassName}}(found, doc);
                    }
                }
            }
            """;
    }

    private static string GetSegId(SegmentDesc[] segments, string segClassName)
    {
        foreach (var seg in segments)
            if (seg.ClassName == segClassName)
                return seg.SegmentId;
        return segClassName.Replace("Segment", "");
    }

    // ── Schema loading ────────────────────────────────────────────────────

    private static (SegmentDesc[] Segments, TxDesc[] Transactions) LoadSchema()
    {
        var json = ReadEmbeddedSchema();
        return (ParseSegments(json), ParseTransactions(json));
    }

    private static string ReadEmbeddedSchema()
    {
        var asm = typeof(X12TransactionGenerator).Assembly;
        const string resourceName = "X12Net.SourceGenerator.schemas.schema.json";
        using var stream = asm.GetManifestResourceStream(resourceName)
            ?? throw new InvalidOperationException(
                $"Embedded resource '{resourceName}' not found. " +
                $"Available: {string.Join(", ", asm.GetManifestResourceNames())}");
        using var reader = new System.IO.StreamReader(stream);
        return reader.ReadToEnd();
    }

    // ── Minimal JSON parser (no external dependencies) ────────────────────

    /// <summary>
    /// Returns the content between the outer <c>[</c> and <c>]</c> of the named array key.
    /// Handles nested objects and arrays by counting braces and brackets.
    /// </summary>
    private static string ExtractArray(string json, string key)
    {
        int keyIdx = json.IndexOf($"\"{key}\"", StringComparison.Ordinal);
        if (keyIdx < 0) return string.Empty;
        int bracketIdx = json.IndexOf('[', keyIdx);
        if (bracketIdx < 0) return string.Empty;

        int depth = 0, end = -1;
        for (int i = bracketIdx; i < json.Length; i++)
        {
            char c = json[i];
            if (c == '"') { i++; while (i < json.Length && json[i] != '"') { if (json[i] == '\\') i++; i++; } }
            else if (c == '[') depth++;
            else if (c == ']') { if (--depth == 0) { end = i; break; } }
        }
        return end >= 0 ? json.Substring(bracketIdx + 1, end - bracketIdx - 1) : string.Empty;
    }

    /// <summary>Splits a JSON array body into individual <c>{...}</c> object strings.</summary>
    private static IEnumerable<string> SplitObjects(string arrayContent)
    {
        int i = 0;
        while (i < arrayContent.Length)
        {
            int open = arrayContent.IndexOf('{', i);
            if (open < 0) yield break;

            int depth = 0, close = -1;
            for (int j = open; j < arrayContent.Length; j++)
            {
                char c = arrayContent[j];
                if (c == '"') { j++; while (j < arrayContent.Length && arrayContent[j] != '"') { if (arrayContent[j] == '\\') j++; j++; } }
                else if (c == '{') depth++;
                else if (c == '}') { if (--depth == 0) { close = j; break; } }
            }
            if (close < 0) yield break;
            yield return arrayContent.Substring(open, close - open + 1);
            i = close + 1;
        }
    }

    private static string ExtractString(string obj, string key)
    {
        var m = Regex.Match(obj, $@"""{Regex.Escape(key)}""\s*:\s*""([^""]*)""");
        return m.Success ? m.Groups[1].Value : string.Empty;
    }

    private static int ExtractInt(string obj, string key)
    {
        var m = Regex.Match(obj, $@"""{Regex.Escape(key)}""\s*:\s*(\d+)");
        return m.Success && int.TryParse(m.Groups[1].Value, out var v) ? v : 0;
    }

    private static SegmentDesc[] ParseSegments(string json)
    {
        var result = new List<SegmentDesc>();
        foreach (var segObj in SplitObjects(ExtractArray(json, "segments")))
        {
            var props = new List<PropDesc>();
            foreach (var propObj in SplitObjects(ExtractArray(segObj, "properties")))
                props.Add(new PropDesc(
                    ExtractString(propObj, "name"),
                    ExtractInt(propObj, "index"),
                    ExtractString(propObj, "doc")));
            result.Add(new SegmentDesc(
                ExtractString(segObj, "segmentId"),
                ExtractString(segObj, "className"),
                props.ToArray()));
        }
        return result.ToArray();
    }

    private static TxDesc[] ParseTransactions(string json)
    {
        var result = new List<TxDesc>();
        foreach (var txObj in SplitObjects(ExtractArray(json, "transactions")))
            result.Add(new TxDesc(
                ExtractString(txObj, "className"),
                ExtractString(txObj, "txSetId"),
                ExtractString(txObj, "segmentClassName"),
                ExtractString(txObj, "propertyName")));
        return result.ToArray();
    }

    // ── Descriptor records ────────────────────────────────────────────────

    private sealed record PropDesc(string Name, int Index, string Doc);

    private sealed record TxDesc(
        string ClassName, string TxSetId, string SegClassName, string PropertyName);

    private sealed class SegmentDesc
    {
        public string     SegmentId  { get; }
        public string     ClassName  { get; }
        public PropDesc[] Properties { get; }

        public SegmentDesc(string segmentId, string className, params PropDesc[] properties)
        {
            SegmentId  = segmentId;
            ClassName  = className;
            Properties = properties;
        }
    }
}
