using Microsoft.CodeAnalysis;

namespace X12Net.SourceGenerator;

/// <summary>
/// Roslyn incremental source generator that emits strongly-typed X12 transaction-set
/// classes and their key segment wrappers for all built-in schemas.
/// </summary>
[Generator]
public sealed class X12TransactionGenerator : IIncrementalGenerator
{
    // ── Descriptor tables ─────────────────────────────────────────────────

    private static readonly SegmentDesc[] Segments =
    {
        new("AK1", "AK1Segment",
            new PropDesc("FunctionalIdentifierCode", 1, "Functional Identifier Code"),
            new PropDesc("GroupControlNumber",        2, "Group Control Number")),

        new("CLP", "CLPSegment",
            new PropDesc("PatientControlNumber", 1, "Patient Control Number"),
            new PropDesc("ClaimStatusCode",      2, "Claim Status Code")),

        new("CLM", "ClmSegment",
            new PropDesc("PatientControlNumber",   1, "Patient Control Number (CLM01)"),
            new PropDesc("TotalClaimChargeAmount", 2, "Total Claim Charge Amount (CLM02)")),

        new("EQ", "EQSegment",
            new PropDesc("ServiceTypeCode", 1, "Service Type Code (EQ01)")),

        new("EB", "EBSegment",
            new PropDesc("EligibilityOrBenefitInformation", 1, "Eligibility or Benefit Information (EB01)")),

        new("INS", "INSSegment",
            new PropDesc("MemberIndicator",            1, "Member Indicator (INS01)"),
            new PropDesc("IndividualRelationshipCode", 2, "Individual Relationship Code (INS02)")),

        new("STC", "STCSegment",
            new PropDesc("HealthCareClaimStatus", 1, "Health Care Claim Status composite (STC01)"),
            new PropDesc("StatusEffectiveDate",   2, "Status Effective Date (STC02)"),
            new PropDesc("ActionCode",            3, "Action Code (STC03)"),
            new PropDesc("MonetaryAmount",        4, "Monetary Amount (STC04)")),
    };

    // Each entry: (className, transactionSetId, segmentClassName, propertyName)
    private static readonly TxDesc[] Transactions =
    {
        new("Ts999",  "999",  "AK1Segment", "AK1"),
        new("Ts835",  "835",  "CLPSegment", "CLP"),
        new("Ts837P", "837",  "ClmSegment", "CLM"),
        new("Ts837I", "837",  "ClmSegment", "CLM"),
        new("Ts837D", "837",  "ClmSegment", "CLM"),
        new("Ts270",  "270",  "EQSegment",  "EQ"),
        new("Ts271",  "271",  "EBSegment",  "EB"),
        new("Ts834",  "834",  "INSSegment", "INS"),
        new("Ts276",  "276",  "STCSegment", "STC"),
        new("Ts277",  "277",  "STCSegment", "STC"),
    };

    // ── IIncrementalGenerator ─────────────────────────────────────────────

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static ctx =>
        {
            foreach (var seg in Segments)
                ctx.AddSource($"{seg.ClassName}.g.cs", BuildSegmentSource(seg));

            foreach (var tx in Transactions)
                ctx.AddSource($"{tx.ClassName}.g.cs", BuildTxSource(tx));
        });
    }

    // ── Code emission ─────────────────────────────────────────────────────

    private static string BuildSegmentSource(SegmentDesc seg)
    {
        var props = new System.Text.StringBuilder();
        foreach (var p in seg.Properties)
        {
            props.AppendLine($"        /// <summary>{p.Doc}.</summary>");
            props.AppendLine($"        public string {p.Name} => Raw[{p.Index}];");
            props.AppendLine();
        }

        return $$"""
            // <auto-generated/>
            #nullable enable
            namespace X12Net.Transactions
            {
                /// <summary>Typed wrapper for the {{seg.SegmentId}} segment.</summary>
                public sealed class {{seg.ClassName}}
                {
                    internal {{seg.ClassName}}(global::X12Net.Core.X12Segment raw) => Raw = raw;

                    /// <summary>The underlying raw segment.</summary>
                    public global::X12Net.Core.X12Segment Raw { get; }

            {{props}}    }
            }
            """;
    }

    private static string BuildTxSource(TxDesc tx)
    {
        var segId = GetSegId(tx.SegClassName);
        return $$"""
            // <auto-generated/>
            #nullable enable
            namespace X12Net.Transactions
            {
                /// <summary>Strongly-typed wrapper for the {{tx.TxSetId}} transaction set.</summary>
                public sealed class {{tx.ClassName}}
                {
                    private {{tx.ClassName}}({{tx.SegClassName}}? keySegment, global::X12Net.DOM.X12Document document)
                    {
                        {{tx.PropertyName}} = keySegment;
                        Document            = document;
                    }

                    /// <summary>The first typed {{segId}} segment, or <c>null</c> if none is present.</summary>
                    public {{tx.SegClassName}}? {{tx.PropertyName}} { get; }

                    /// <summary>The underlying generic document for full access.</summary>
                    public global::X12Net.DOM.X12Document Document { get; }

                    /// <summary>Returns all {{segId}} segments in document order.</summary>
                    public global::System.Collections.Generic.IEnumerable<{{tx.SegClassName}}> All{{tx.PropertyName}}()
                    {
                        foreach (var seg in Document.AllSegments("{{segId}}"))
                            yield return new {{tx.SegClassName}}(new global::X12Net.Core.X12Segment(seg.SegmentId, seg.Elements));
                    }

                    /// <summary>Parses a {{tx.TxSetId}} transaction from raw EDI X12 text.</summary>
                    public static {{tx.ClassName}} Parse(string input)
                    {
                        var doc = global::X12Net.DOM.X12Document.Parse(input);
                        using var reader = new global::X12Net.IO.X12Reader(input, doc.Delimiters);
                        {{tx.SegClassName}}? found = null;
                        foreach (var seg in reader.ReadAllSegments())
                        {
                            if (seg.SegmentId == "{{segId}}")
                            {
                                found = new {{tx.SegClassName}}(seg);
                                break;
                            }
                        }
                        return new {{tx.ClassName}}(found, doc);
                    }
                }
            }
            """;
    }

    // Derives the segment ID from the segment class name (e.g., "CLPSegment" → "CLP").
    private static string GetSegId(string segClassName)
    {
        foreach (var seg in Segments)
            if (seg.ClassName == segClassName)
                return seg.SegmentId;
        return segClassName.Replace("Segment", "");
    }

    // ── Descriptor records ────────────────────────────────────────────────

    private sealed record PropDesc(string Name, int Index, string Doc);

    private sealed record TxDesc(
        string ClassName, string TxSetId, string SegClassName, string PropertyName);

    private sealed class SegmentDesc
    {
        public string     SegmentId  { get; }
        public string     ClassName  { get; }
        public PropDesc[] Properties { get; }

        public SegmentDesc(string segmentId, string className, params PropDesc[] properties)
        {
            SegmentId  = segmentId;
            ClassName  = className;
            Properties = properties;
        }
    }
}
