using Microsoft.CodeAnalysis;

namespace X12Net.SourceGenerator;

/// <summary>
/// Roslyn incremental source generator that emits strongly-typed X12 transaction-set
/// classes and their key segment wrappers for all built-in schemas.
/// </summary>
[Generator]
public sealed class X12TransactionGenerator : IIncrementalGenerator
{
    // ── Descriptor tables ─────────────────────────────────────────────────

    // Each entry: (segmentId, className, prop1Name, prop1DocElement, prop2Name, prop2DocElement, prop3Name, prop3DocElement)
    // Props map to element index 1, 2, 4 respectively (0 means "not exposed").
    private static readonly SegmentDesc[] Segments =
    {
        new("AK1", "AK1Segment",
            "FunctionalIdentifierCode", 1, "Functional Identifier Code",
            "GroupControlNumber",        2, "Group Control Number",
            null, 0, null),

        new("CLP", "CLPSegment",
            "PatientControlNumber", 1, "Patient Control Number",
            "ClaimStatusCode",      2, "Claim Status Code",
            null, 0, null),

        new("CLM", "ClmSegment",
            "PatientControlNumber",     1, "Patient Control Number (CLM01)",
            "TotalClaimChargeAmount",   2, "Total Claim Charge Amount (CLM02)",
            null, 0, null),

        new("EQ", "EQSegment",
            "ServiceTypeCode", 1, "Service Type Code (EQ01)",
            null, 0, null,
            null, 0, null),

        new("EB", "EBSegment",
            "EligibilityOrBenefitInformation", 1, "Eligibility or Benefit Information (EB01)",
            null, 0, null,
            null, 0, null),

        new("INS", "INSSegment",
            "MemberIndicator",             1, "Member Indicator (INS01)",
            "IndividualRelationshipCode",  2, "Individual Relationship Code (INS02)",
            null, 0, null),

        new("STC", "STCSegment",
            "HealthCareClaimStatus", 1, "Health Care Claim Status composite (STC01)",
            "StatusEffectiveDate",   2, "Status Effective Date (STC02)",
            "MonetaryAmount",        4, "Monetary Amount (STC04)"),
    };

    // Each entry: (className, transactionSetId, segmentClassName, propertyName)
    private static readonly TxDesc[] Transactions =
    {
        new("Ts999",  "999",  "AK1Segment", "AK1"),
        new("Ts835",  "835",  "CLPSegment", "CLP"),
        new("Ts837P", "837",  "ClmSegment", "CLM"),
        new("Ts837I", "837",  "ClmSegment", "CLM"),
        new("Ts837D", "837",  "ClmSegment", "CLM"),
        new("Ts270",  "270",  "EQSegment",  "EQ"),
        new("Ts271",  "271",  "EBSegment",  "EB"),
        new("Ts834",  "834",  "INSSegment", "INS"),
        new("Ts276",  "276",  "STCSegment", "STC"),
        new("Ts277",  "277",  "STCSegment", "STC"),
    };

    // ── IIncrementalGenerator ─────────────────────────────────────────────

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static ctx =>
        {
            // Emit one file per unique segment class
            foreach (var seg in Segments)
                ctx.AddSource($"{seg.ClassName}.g.cs", BuildSegmentSource(seg));

            // Emit one file per transaction class
            foreach (var tx in Transactions)
                ctx.AddSource($"{tx.ClassName}.g.cs", BuildTxSource(tx));
        });
    }

    // ── Code emission ─────────────────────────────────────────────────────

    private static string BuildSegmentSource(SegmentDesc seg)
    {
        var props = new System.Text.StringBuilder();

        void AddProp(string? name, int idx, string? doc)
        {
            if (name is null) return;
            props.AppendLine($"        /// <summary>{doc}.</summary>");
            props.AppendLine($"        public string {name} => Raw[{idx}];");
            props.AppendLine();
        }

        AddProp(seg.Prop1Name, seg.Prop1Index, seg.Prop1Doc);
        AddProp(seg.Prop2Name, seg.Prop2Index, seg.Prop2Doc);
        AddProp(seg.Prop3Name, seg.Prop3Index, seg.Prop3Doc);

        return $$"""
            // <auto-generated/>
            #nullable enable
            namespace X12Net.Transactions
            {
                /// <summary>Typed wrapper for the {{seg.SegmentId}} segment.</summary>
                public sealed class {{seg.ClassName}}
                {
                    internal {{seg.ClassName}}(global::X12Net.Core.X12Segment raw) => Raw = raw;

                    /// <summary>The underlying raw segment.</summary>
                    public global::X12Net.Core.X12Segment Raw { get; }

            {{props}}    }
            }
            """;
    }

    private static string BuildTxSource(TxDesc tx)
    {
        var segId = GetSegId(tx.SegClassName);
        return $$"""
            // <auto-generated/>
            #nullable enable
            namespace X12Net.Transactions
            {
                /// <summary>Strongly-typed wrapper for the {{tx.TxSetId}} transaction set.</summary>
                public sealed class {{tx.ClassName}}
                {
                    private {{tx.ClassName}}({{tx.SegClassName}}? keySegment, global::X12Net.DOM.X12Document document)
                    {
                        {{tx.PropertyName}} = keySegment;
                        Document            = document;
                    }

                    /// <summary>The first typed {{segId}} segment, or <c>null</c> if none is present.</summary>
                    public {{tx.SegClassName}}? {{tx.PropertyName}} { get; }

                    /// <summary>The underlying generic document for full access.</summary>
                    public global::X12Net.DOM.X12Document Document { get; }

                    /// <summary>Returns all {{segId}} segments in document order.</summary>
                    public global::System.Collections.Generic.IEnumerable<{{tx.SegClassName}}> All{{tx.PropertyName}}()
                    {
                        using var reader = new global::X12Net.IO.X12Reader(Document.ToString(), Document.Delimiters);
                        foreach (var seg in reader.ReadAllSegments())
                        {
                            if (seg.SegmentId == "{{segId}}")
                                yield return new {{tx.SegClassName}}(seg);
                        }
                    }

                    /// <summary>Parses a {{tx.TxSetId}} transaction from raw EDI X12 text.</summary>
                    public static {{tx.ClassName}} Parse(string input)
                    {
                        var doc = global::X12Net.DOM.X12Document.Parse(input);
                        using var reader = new global::X12Net.IO.X12Reader(input, doc.Delimiters);
                        {{tx.SegClassName}}? found = null;
                        foreach (var seg in reader.ReadAllSegments())
                        {
                            if (seg.SegmentId == "{{segId}}")
                            {
                                found = new {{tx.SegClassName}}(seg);
                                break;
                            }
                        }
                        return new {{tx.ClassName}}(found, doc);
                    }
                }
            }
            """;
    }

    // Derives the segment ID from the segment class name (e.g., "CLPSegment" → "CLP").
    private static string GetSegId(string segClassName)
    {
        foreach (var seg in Segments)
            if (seg.ClassName == segClassName)
                return seg.SegmentId;
        return segClassName.Replace("Segment", "");
    }

    // ── Descriptor records ────────────────────────────────────────────────

    private sealed class SegmentDesc
    {
        public string SegmentId { get; }
        public string ClassName { get; }
        public string? Prop1Name { get; }
        public int Prop1Index { get; }
        public string? Prop1Doc { get; }
        public string? Prop2Name { get; }
        public int Prop2Index { get; }
        public string? Prop2Doc { get; }
        public string? Prop3Name { get; }
        public int Prop3Index { get; }
        public string? Prop3Doc { get; }

        public SegmentDesc(
            string segmentId, string className,
            string? p1Name, int p1Idx, string? p1Doc,
            string? p2Name, int p2Idx, string? p2Doc,
            string? p3Name, int p3Idx, string? p3Doc)
        {
            SegmentId  = segmentId; ClassName = className;
            Prop1Name  = p1Name;   Prop1Index = p1Idx; Prop1Doc = p1Doc;
            Prop2Name  = p2Name;   Prop2Index = p2Idx; Prop2Doc = p2Doc;
            Prop3Name  = p3Name;   Prop3Index = p3Idx; Prop3Doc = p3Doc;
        }
    }

    private sealed class TxDesc
    {
        public string ClassName    { get; }
        public string TxSetId      { get; }
        public string SegClassName { get; }
        public string PropertyName { get; }

        public TxDesc(string className, string txSetId, string segClassName, string propertyName)
        {
            ClassName    = className;
            TxSetId      = txSetId;
            SegClassName = segClassName;
            PropertyName = propertyName;
        }
    }
}
